[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
escrow_anchor_v1 = "FTYviMqzWVj9b9jbFSwiSrGmxLwo4MKEFSruLpdRYTHW"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
